<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="LAPTOP-VBVJH9CB" name="com.AutomationPractice.Sampletest" tests="6" failures="0" timestamp="2021-08-20T16:19:50 IST" time="0.013" errors="1">
  <testcase name="divide" time="0.001" classname="com.AutomationPractice.Sampletest">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.AutomationPractice.Sampletest.divide(Sampletest.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- divide -->
  <system-out/>
  <testcase name="divide" time="0.001" classname="com.AutomationPractice.Sampletest">
    <skipped/>
  </testcase> <!-- divide -->
  <system-out/>
  <testcase name="divide" time="0.001" classname="com.AutomationPractice.Sampletest">
    <skipped/>
  </testcase> <!-- divide -->
  <system-out/>
  <testcase name="demo" time="0.008" classname="com.AutomationPractice.Sampletest"/>
  <system-out/>
  <testcase name="divide" time="0.001" classname="com.AutomationPractice.Sampletest">
    <skipped/>
  </testcase> <!-- divide -->
  <system-out/>
  <testcase name="divide" time="0.001" classname="com.AutomationPractice.Sampletest">
    <skipped/>
  </testcase> <!-- divide -->
  <system-out/>
</testsuite> <!-- com.AutomationPractice.Sampletest -->
